// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ildomm/linx_challenge/models"
)

// CreateURLOKCode is the HTTP code returned for type CreateURLOK
const CreateURLOKCode int = 200

/*CreateURLOK Successful operation

swagger:response createUrlOK
*/
type CreateURLOK struct {

	/*
	  In: Body
	*/
	Payload *models.URL `json:"body,omitempty"`
}

// NewCreateURLOK creates CreateURLOK with default headers values
func NewCreateURLOK() *CreateURLOK {

	return &CreateURLOK{}
}

// WithPayload adds the payload to the create Url o k response
func (o *CreateURLOK) WithPayload(payload *models.URL) *CreateURLOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Url o k response
func (o *CreateURLOK) SetPayload(payload *models.URL) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateURLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateURLNotFoundCode is the HTTP code returned for type CreateURLNotFound
const CreateURLNotFoundCode int = 404

/*CreateURLNotFound User not found

swagger:response createUrlNotFound
*/
type CreateURLNotFound struct {
}

// NewCreateURLNotFound creates CreateURLNotFound with default headers values
func NewCreateURLNotFound() *CreateURLNotFound {

	return &CreateURLNotFound{}
}

// WriteResponse to the client
func (o *CreateURLNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*CreateURLDefault error

swagger:response createUrlDefault
*/
type CreateURLDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewCreateURLDefault creates CreateURLDefault with default headers values
func NewCreateURLDefault(code int) *CreateURLDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateURLDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create Url default response
func (o *CreateURLDefault) WithStatusCode(code int) *CreateURLDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create Url default response
func (o *CreateURLDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create Url default response
func (o *CreateURLDefault) WithPayload(payload *models.GeneralError) *CreateURLDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Url default response
func (o *CreateURLDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateURLDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
