// Code generated by go-swagger; DO NOT EDIT.

package urls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteURLOKCode is the HTTP code returned for type DeleteURLOK
const DeleteURLOKCode int = 200

/*DeleteURLOK Successful operation

swagger:response deleteUrlOK
*/
type DeleteURLOK struct {
}

// NewDeleteURLOK creates DeleteURLOK with default headers values
func NewDeleteURLOK() *DeleteURLOK {

	return &DeleteURLOK{}
}

// WriteResponse to the client
func (o *DeleteURLOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteURLNotFoundCode is the HTTP code returned for type DeleteURLNotFound
const DeleteURLNotFoundCode int = 404

/*DeleteURLNotFound Url not found

swagger:response deleteUrlNotFound
*/
type DeleteURLNotFound struct {
}

// NewDeleteURLNotFound creates DeleteURLNotFound with default headers values
func NewDeleteURLNotFound() *DeleteURLNotFound {

	return &DeleteURLNotFound{}
}

// WriteResponse to the client
func (o *DeleteURLNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
