// Code generated by go-swagger; DO NOT EDIT.

package urls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RedirectURLFoundCode is the HTTP code returned for type RedirectURLFound
const RedirectURLFoundCode int = 302

/*RedirectURLFound successful operation

swagger:response redirectUrlFound
*/
type RedirectURLFound struct {
	/*

	 */
	Location string `json:"Location"`
}

// NewRedirectURLFound creates RedirectURLFound with default headers values
func NewRedirectURLFound() *RedirectURLFound {

	return &RedirectURLFound{}
}

// WithLocation adds the location to the redirect Url found response
func (o *RedirectURLFound) WithLocation(location string) *RedirectURLFound {
	o.Location = location
	return o
}

// SetLocation sets the location to the redirect Url found response
func (o *RedirectURLFound) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *RedirectURLFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// RedirectURLNotFoundCode is the HTTP code returned for type RedirectURLNotFound
const RedirectURLNotFoundCode int = 404

/*RedirectURLNotFound Url not found

swagger:response redirectUrlNotFound
*/
type RedirectURLNotFound struct {
}

// NewRedirectURLNotFound creates RedirectURLNotFound with default headers values
func NewRedirectURLNotFound() *RedirectURLNotFound {

	return &RedirectURLNotFound{}
}

// WriteResponse to the client
func (o *RedirectURLNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
