// Code generated by go-swagger; DO NOT EDIT.

package urls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RedirectURLMovedPermanentlyCode is the HTTP code returned for type RedirectURLMovedPermanently
const RedirectURLMovedPermanentlyCode int = 301

/*RedirectURLMovedPermanently successful operation

swagger:response redirectUrlMovedPermanently
*/
type RedirectURLMovedPermanently struct {
}

// NewRedirectURLMovedPermanently creates RedirectURLMovedPermanently with default headers values
func NewRedirectURLMovedPermanently() *RedirectURLMovedPermanently {

	return &RedirectURLMovedPermanently{}
}

// WriteResponse to the client
func (o *RedirectURLMovedPermanently) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(301)
}

// RedirectURLNotFoundCode is the HTTP code returned for type RedirectURLNotFound
const RedirectURLNotFoundCode int = 404

/*RedirectURLNotFound Url not found

swagger:response redirectUrlNotFound
*/
type RedirectURLNotFound struct {
}

// NewRedirectURLNotFound creates RedirectURLNotFound with default headers values
func NewRedirectURLNotFound() *RedirectURLNotFound {

	return &RedirectURLNotFound{}
}

// WriteResponse to the client
func (o *RedirectURLNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
