// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ildomm/linx_challenge/restapi/operations/stats"
	"github.com/ildomm/linx_challenge/restapi/operations/urls"
	"github.com/ildomm/linx_challenge/restapi/operations/users"
)

// NewPocAPI creates a new Poc instance
func NewPocAPI(spec *loads.Document) *PocAPI {
	return &PocAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		UsersCreateURLHandler: users.CreateURLHandlerFunc(func(params users.CreateURLParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersCreateURL has not yet been implemented")
		}),
		UsersCreateUserHandler: users.CreateUserHandlerFunc(func(params users.CreateUserParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersCreateUser has not yet been implemented")
		}),
		UrlsDeleteURLHandler: urls.DeleteURLHandlerFunc(func(params urls.DeleteURLParams) middleware.Responder {
			return middleware.NotImplemented("operation UrlsDeleteURL has not yet been implemented")
		}),
		UsersDeleteUserHandler: users.DeleteUserHandlerFunc(func(params users.DeleteUserParams) middleware.Responder {
			return middleware.NotImplemented("operation UsersDeleteUser has not yet been implemented")
		}),
		StatsGetSystemStatsHandler: stats.GetSystemStatsHandlerFunc(func(params stats.GetSystemStatsParams) middleware.Responder {
			return middleware.NotImplemented("operation StatsGetSystemStats has not yet been implemented")
		}),
		StatsGetURLStatsHandler: stats.GetURLStatsHandlerFunc(func(params stats.GetURLStatsParams) middleware.Responder {
			return middleware.NotImplemented("operation StatsGetURLStats has not yet been implemented")
		}),
		StatsGetUserStatsHandler: stats.GetUserStatsHandlerFunc(func(params stats.GetUserStatsParams) middleware.Responder {
			return middleware.NotImplemented("operation StatsGetUserStats has not yet been implemented")
		}),
		OptionsAllowHandler: OptionsAllowHandlerFunc(func(params OptionsAllowParams) middleware.Responder {
			return middleware.NotImplemented("operation OptionsAllow has not yet been implemented")
		}),
		UrlsRedirectURLHandler: urls.RedirectURLHandlerFunc(func(params urls.RedirectURLParams) middleware.Responder {
			return middleware.NotImplemented("operation UrlsRedirectURL has not yet been implemented")
		}),
	}
}

/*PocAPI This is the API specification for Linx challenge project */
type PocAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// UsersCreateURLHandler sets the operation handler for the create Url operation
	UsersCreateURLHandler users.CreateURLHandler
	// UsersCreateUserHandler sets the operation handler for the create user operation
	UsersCreateUserHandler users.CreateUserHandler
	// UrlsDeleteURLHandler sets the operation handler for the delete Url operation
	UrlsDeleteURLHandler urls.DeleteURLHandler
	// UsersDeleteUserHandler sets the operation handler for the delete user operation
	UsersDeleteUserHandler users.DeleteUserHandler
	// StatsGetSystemStatsHandler sets the operation handler for the get system stats operation
	StatsGetSystemStatsHandler stats.GetSystemStatsHandler
	// StatsGetURLStatsHandler sets the operation handler for the get Url stats operation
	StatsGetURLStatsHandler stats.GetURLStatsHandler
	// StatsGetUserStatsHandler sets the operation handler for the get user stats operation
	StatsGetUserStatsHandler stats.GetUserStatsHandler
	// OptionsAllowHandler sets the operation handler for the options allow operation
	OptionsAllowHandler OptionsAllowHandler
	// UrlsRedirectURLHandler sets the operation handler for the redirect Url operation
	UrlsRedirectURLHandler urls.RedirectURLHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *PocAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *PocAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *PocAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *PocAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *PocAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *PocAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *PocAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the PocAPI
func (o *PocAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.UsersCreateURLHandler == nil {
		unregistered = append(unregistered, "users.CreateURLHandler")
	}

	if o.UsersCreateUserHandler == nil {
		unregistered = append(unregistered, "users.CreateUserHandler")
	}

	if o.UrlsDeleteURLHandler == nil {
		unregistered = append(unregistered, "urls.DeleteURLHandler")
	}

	if o.UsersDeleteUserHandler == nil {
		unregistered = append(unregistered, "users.DeleteUserHandler")
	}

	if o.StatsGetSystemStatsHandler == nil {
		unregistered = append(unregistered, "stats.GetSystemStatsHandler")
	}

	if o.StatsGetURLStatsHandler == nil {
		unregistered = append(unregistered, "stats.GetURLStatsHandler")
	}

	if o.StatsGetUserStatsHandler == nil {
		unregistered = append(unregistered, "stats.GetUserStatsHandler")
	}

	if o.OptionsAllowHandler == nil {
		unregistered = append(unregistered, "OptionsAllowHandler")
	}

	if o.UrlsRedirectURLHandler == nil {
		unregistered = append(unregistered, "urls.RedirectURLHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *PocAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *PocAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *PocAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *PocAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *PocAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *PocAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the poc API
func (o *PocAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *PocAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users/{userId}/urls"] = users.NewCreateURL(o.context, o.UsersCreateURLHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users"] = users.NewCreateUser(o.context, o.UsersCreateUserHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/urls/{id}"] = urls.NewDeleteURL(o.context, o.UrlsDeleteURLHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/user/{userId}"] = users.NewDeleteUser(o.context, o.UsersDeleteUserHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/stats"] = stats.NewGetSystemStats(o.context, o.StatsGetSystemStatsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/stats/{id}"] = stats.NewGetURLStats(o.context, o.StatsGetURLStatsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{userId}/stats"] = stats.NewGetUserStats(o.context, o.StatsGetUserStatsHandler)

	if o.handlers["OPTIONS"] == nil {
		o.handlers["OPTIONS"] = make(map[string]http.Handler)
	}
	o.handlers["OPTIONS"]["/*"] = NewOptionsAllow(o.context, o.OptionsAllowHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/urls/{id}"] = urls.NewRedirectURL(o.context, o.UrlsRedirectURLHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *PocAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *PocAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *PocAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *PocAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
