// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Linx API
This is the API specification for Linx challenge project


    Schemes:
      http
    Host: api.poc.com
    BasePath: /v1
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
