// Code generated by go-swagger; DO NOT EDIT.

package stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetSystemStatsParams creates a new GetSystemStatsParams object
// no default values defined in spec.
func NewGetSystemStatsParams() GetSystemStatsParams {

	return GetSystemStatsParams{}
}

// GetSystemStatsParams contains all the bound params for the get system stats operation
// typically these are obtained from a http.Request
//
// swagger:parameters getSystemStats
type GetSystemStatsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSystemStatsParams() beforehand.
func (o *GetSystemStatsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
