// Code generated by go-swagger; DO NOT EDIT.

package stats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUserStatsHandlerFunc turns a function with the right signature into a get user stats handler
type GetUserStatsHandlerFunc func(GetUserStatsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserStatsHandlerFunc) Handle(params GetUserStatsParams) middleware.Responder {
	return fn(params)
}

// GetUserStatsHandler interface for that can handle valid get user stats params
type GetUserStatsHandler interface {
	Handle(GetUserStatsParams) middleware.Responder
}

// NewGetUserStats creates a new http.Handler for the get user stats operation
func NewGetUserStats(ctx *middleware.Context, handler GetUserStatsHandler) *GetUserStats {
	return &GetUserStats{Context: ctx, Handler: handler}
}

/*GetUserStats swagger:route GET /users/{userId}/stats stats getUserStats

Get user statistics

Get user statistics

*/
type GetUserStats struct {
	Context *middleware.Context
	Handler GetUserStatsHandler
}

func (o *GetUserStats) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserStatsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
