// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Stats stats
// swagger:model Stats
type Stats struct {

	// hits
	Hits int64 `json:"hits,omitempty"`

	// top urls
	TopUrls []*URL `json:"topUrls"`

	// url count
	URLCount int64 `json:"urlCount,omitempty"`
}

// Validate validates this stats
func (m *Stats) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTopUrls(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Stats) validateTopUrls(formats strfmt.Registry) error {

	if swag.IsZero(m.TopUrls) { // not required
		return nil
	}

	for i := 0; i < len(m.TopUrls); i++ {
		if swag.IsZero(m.TopUrls[i]) { // not required
			continue
		}

		if m.TopUrls[i] != nil {
			if err := m.TopUrls[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("topUrls" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Stats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Stats) UnmarshalBinary(b []byte) error {
	var res Stats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
